"""Shared files for ``chirp new`` (pyproject, migrations, theme hook)."""

PYPROJECT_TOML = """\
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "Generated by chirp new"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bengal-chirp>=0.5.0",
]

[project.optional-dependencies]
ui = ["chirp-ui>=0.5.0"]
auth = ["argon2-cffi>=23.1.0", "itsdangerous>=2.2.0"]
forms = ["python-multipart>=0.0.18"]
"""

MIGRATIONS_README = """# Migrations

Place SQL migration scripts here when using ``chirp.data`` or another migration tool.
"""

THEME_CSS_STUB = """/* Optional ChirpUI design-token overrides — see chirp-ui docs/TOKENS.md */
"""

APP_THEME_CSS_FALLBACK = """/* App-owned ChirpUI theme tokens.
 *
 * Generated because this installed chirp-ui package does not include
 * themes/app-theme-starter.css yet. Load after /static/chirpui.css.
 * Keep app brand values here; Chirp and Chirp-UI own only the token names.
 */

@layer app.theme {
    :root {
        color-scheme: light dark;
    }

    [data-theme="light"] {
        color-scheme: light;
    }

    [data-theme="dark"] {
        color-scheme: dark;
    }

    @media (prefers-color-scheme: light) {
        [data-theme="system"] {
            color-scheme: light;
        }
    }

    @media (prefers-color-scheme: dark) {
        [data-theme="system"] {
            color-scheme: dark;
        }
    }
}
"""
