"""Shared files for ``chirp new`` (pyproject, migrations, theme hook)."""

PYPROJECT_TOML = """\
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "Generated by chirp new"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bengal-chirp>=0.2.1",
]

[project.optional-dependencies]
ui = ["chirp-ui>=0.2.0"]
auth = ["argon2-cffi>=23.1.0", "itsdangerous>=2.2.0"]
forms = ["python-multipart>=0.0.18"]
"""

MIGRATIONS_README = """# Migrations

Place SQL migration scripts here when using ``chirp.data`` or another migration tool.
"""

THEME_CSS_STUB = """/* Optional ChirpUI design-token overrides — see chirp-ui docs/TOKENS.md */
"""
