"""Shared files for ``chirp new`` (pyproject, agent guidance, migrations, theme hook)."""

AGENTS_MD = """\
# AGENTS.md

This is a Chirp app. Chirp renders server-side HTML and uses return types
(`Page`, `Fragment`, `OOB`, `Suspense`, `EventStream`, `ValidationError`) to
declare browser behavior.

## Debugging

When debugging htmx swaps, OOB updates, Suspense blocks, SSE, fragment targets,
or content negotiation, activate debug mode before guessing from screenshots:

- Prefer `chirp dev app:app` when the CLI is available. It forces
  `debug=True` for the running app.
- Otherwise set `AppConfig(debug=True)` temporarily. If this app uses
  `AppConfig.from_env()`, `CHIRP_DEBUG=1` also works.
- Open the app in a browser and press `Ctrl+Shift+D` for Chirp DevTools.
- Press `Ctrl+Shift+K` to inspect inherited/direct/blocked `hx-*` settings.
- Use the SSE tab for native Chirp `EventStream` traces; framework reload
  streams are hidden by default.
- For agent-readable diagnostics, evaluate
  `window.ChirpHtmxDebug.help()` and
  `window.ChirpHtmxDebug.exportRecordsJson()` in the browser context.

Run `chirp check app:app` before shipping changes that touch routes, templates,
fragments, OOB regions, Suspense, or SSE.
"""

PYPROJECT_TOML = """\
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "Generated by chirp new"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bengal-chirp>=0.8.0",
    # SessionMiddleware's default CookieSessionStore signs cookies with
    # itsdangerous; every scaffold wires the Session/CSRF/SecurityHeaders stack.
    "itsdangerous>=2.2.0",
]

[project.optional-dependencies]
ui = ["chirp-ui>=0.11.0"]
auth = ["argon2-cffi>=23.1.0"]
forms = ["python-multipart>=0.0.18"]
"""

MIGRATIONS_README = """# Migrations

Place SQL migration scripts here when using ``chirp.data`` or another migration tool.
"""

THEME_CSS_STUB = """/* Optional app-owned ChirpUI token overrides.
   Loaded after /static/themes/app-theme-starter.css. See chirp-ui docs/APP-THEME.md. */
"""
