"""Skill project scaffolding templates (``--skill``)."""

SKILL_APP_PY = """\
\"\"\"Skill scaffold — signed skill.tool envelopes + secure-by-default stack.\"\"\"

import os
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from chirp import App, AppConfig, Request, Template, secure_stack
from chirp.skill import Skill, use_skill

TEMPLATES_DIR = Path(__file__).parent / \"templates\"

_DEFAULT_SECRET = \"change-me-before-deploying\"
_secret = os.environ.get(\"CHIRP_SECRET_KEY\", _DEFAULT_SECRET)

# Env-driven so the generated app can run in any environment:
#   CHIRP_ENV=production   selects the production security contract track.
#   CHIRP_DEBUG=1          enables dev tooling (defaults on outside production).
_env = os.environ.get(\"CHIRP_ENV\", \"development\")
_debug = os.environ.get(\"CHIRP_DEBUG\", \"1\" if _env != \"production\" else \"0\") not in (
    \"0\",
    \"false\",
    \"False\",
    \"\",
)

config = AppConfig.from_env(
    secret_key=_secret,
    env=_env,
    debug=_debug,
    template_dir=TEMPLATES_DIR,
)
app = App(config=config)

if config.env != \"development\" and config.secret_key == _DEFAULT_SECRET:
    msg = (
        \"Refusing to start in production with default secret key. \"
        \"Set CHIRP_SECRET_KEY to a strong random value.\"
    )
    raise RuntimeError(msg)

for middleware in secure_stack(app.config):
    app.add_middleware(middleware)


def _load_signing_key() -> Ed25519PrivateKey:
    \"\"\"Load a persistent Ed25519 key from env, or generate an ephemeral one.\"\"\"
    raw = os.environ.get(\"CHIRP_SKILL_PRIVATE_KEY\", \"\").strip()
    if raw:
        return Ed25519PrivateKey.from_private_bytes(bytes.fromhex(raw))
    return Ed25519PrivateKey.generate()


_private = _load_signing_key()
_public = _private.public_key().public_bytes_raw()

skill = Skill(
    \"demo\",
    version=\"0.1.0\",
    private_key=_private,
    key_id=os.environ.get(\"CHIRP_SKILL_KEY_ID\", \"demo-1\"),
    public_key=_public,
)


@skill.tool(\"echo\", description=\"Echo a message back to the caller\")
def echo(message: str) -> dict[str, str]:
    return {\"message\": message, \"echoed\": \"true\"}


use_skill(app, skill)


@app.route(\"/\")
async def index(request: Request) -> Template:
    return Template(
        \"index.html\",
        skill_name=skill.name,
        skill_version=skill.version,
        tools=skill.tools,
    )


if __name__ == \"__main__\":
    app.run()
"""

SKILL_INDEX_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ skill_name }} skill</title>
</head>
<body>
    <h1>{{ skill_name }} <small>v{{ skill_version }}</small></h1>
    <p>Signed skill tools mounted via <code>use_skill</code>.</p>
    <h2>Tools</h2>
    <ul>
    {% for tool in tools %}
        <li><code>{{ tool }}</code></li>
    {% end %}
    </ul>
    <p>Point an MCP client at this app&rsquo;s tool surface, or call tools from
    your agent loop. Set <code>CHIRP_SKILL_PRIVATE_KEY</code> (32-byte hex) for
    a stable signing key across restarts.</p>
</body>
</html>
"""

SKILL_ENV_EXAMPLE = """\
CHIRP_SECRET_KEY=change-me-in-production
# Optional: 32-byte Ed25519 private key as hex (64 hex chars).
# Omit to generate an ephemeral key on each process start (dev only).
# CHIRP_SKILL_PRIVATE_KEY=
CHIRP_SKILL_KEY_ID=demo-1
"""

SKILL_TEST_APP_PY = """\
\"\"\"Smoke tests for {name}.\"\"\"

import pytest

from app import app, skill
from chirp.testing import TestClient


@pytest.fixture
def example_app():
    return app


class TestSmoke:
    @pytest.mark.asyncio
    async def test_index(self, example_app) -> None:
        async with TestClient(example_app) as client:
            response = await client.get(\"/\")
            assert response.status == 200
            assert skill.name in response.text
            assert \"echo\" in response.text

    def test_skill_mounted(self) -> None:
        assert \"echo\" in skill.tools
"""

SKILL_PYPROJECT_TOML = """\
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "Generated by chirp new --skill"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bengal-chirp>=0.10.0",
    # SessionMiddleware's default CookieSessionStore signs cookies with
    # itsdangerous; every scaffold wires the Session/CSRF/SecurityHeaders stack.
    "itsdangerous>=2.2.0",
    # Signed skill envelopes (Ed25519).
    "cryptography>=42.0.0",
]

[project.optional-dependencies]
ui = ["chirp-ui>=0.11.4"]
auth = ["argon2-cffi>=23.1.0"]
forms = ["python-multipart>=0.0.18"]
"""
